In [1]:
import pandas as pd
df = pd.read_csv('data.csv')
df

,ID,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,1,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5.0
1,2,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5.0
2,3,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,NaN,0.65,9.8,5.0
3,4,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6.0
4,5,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1596,1597,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6.0
1597,1598,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6.0
1598,1599,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5.0
1599,1600,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6.0
1600,1601,7.2,0.390,0.44,2.6,0.066,22.0,48.0,0.99494,3.30,0.84,11.5,6.0

In [2]:
print(df.isnull().sum())

ID                      0
fixed acidity           1
volatile acidity        0
citric acid             1
residual sugar          0
chlorides               3
free sulfur dioxide     1
total sulfur dioxide    1
density                 1
pH                      1
sulphates               0
alcohol                 0
quality                 1
dtype: int64

In [3]:
df.dropna(inplace=True)

### CHECKING FOR NULL SPACES AFTER DROPPING ROWS WITH NULL INPUTS

In [11]:
print(df.isnull().sum())

ID                      0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [10]:
print(df.duplicated().sum())

0

In [12]:
df.describe()

,ID,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1591.000000,1591.000000,1591.000000,1591.000000,1591.000000,1591.000000,1591.000000,1591.000000,1591.000000,1591.000000,1591.000000,1591.000000,1591.000000
mean,801.060968,8.320616,0.527681,0.271477,2.540761,0.087500,15.861722,46.498429,0.996747,3.311358,0.658611,10.426053,5.637964
std,460.740942,1.740134,0.179045,0.194807,1.413076,0.047175,10.429385,32.998659,0.001889,0.154548,0.169786,1.066706,0.807772
min,1.000000,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,402.500000,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,801.000000,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,1199.500000,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997845,3.400000,0.730000,11.100000,6.000000
max,1601.000000,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [13]:
df['ID'].describe()

count    1591.000000
mean      801.060968
std       460.740942
min         1.000000
25%       402.500000
50%       801.000000
75%      1199.500000
max      1601.000000
Name: ID, dtype: float64

In [14]:
df['fixed acidity'].describe()

count    1591.000000
mean        8.320616
std         1.740134
min         4.600000
25%         7.100000
50%         7.900000
75%         9.200000
max        15.900000
Name: fixed acidity, dtype: float64

In [15]:
df['volatile acidity'].describe()

count    1591.000000
mean        0.527681
std         0.179045
min         0.120000
25%         0.390000
50%         0.520000
75%         0.640000
max         1.580000
Name: volatile acidity, dtype: float64

In [16]:
df['citric acid'].describe()

count    1591.000000
mean        0.271477
std         0.194807
min         0.000000
25%         0.090000
50%         0.260000
75%         0.420000
max         1.000000
Name: citric acid, dtype: float64

In [17]:
df['residual sugar'].describe()

count    1591.000000
mean        2.540761
std         1.413076
min         0.900000
25%         1.900000
50%         2.200000
75%         2.600000
max        15.500000
Name: residual sugar, dtype: float64

In [18]:
df['chlorides'].describe()

count    1591.000000
mean        0.087500
std         0.047175
min         0.012000
25%         0.070000
50%         0.079000
75%         0.090000
max         0.611000
Name: chlorides, dtype: float64

In [19]:
df['free sulfur dioxide'].describe()

count    1591.000000
mean       15.861722
std        10.429385
min         1.000000
25%         7.000000
50%        14.000000
75%        21.000000
max        72.000000
Name: free sulfur dioxide, dtype: float64

In [20]:
df['density'].describe()

count    1591.000000
mean        0.996747
std         0.001889
min         0.990070
25%         0.995600
50%         0.996750
75%         0.997845
max         1.003690
Name: density, dtype: float64

In [21]:
df['pH'].describe()

count    1591.000000
mean        3.311358
std         0.154548
min         2.740000
25%         3.210000
50%         3.310000
75%         3.400000
max         4.010000
Name: pH, dtype: float64

In [22]:
df['sulphates'].describe()

count    1591.000000
mean        0.658611
std         0.169786
min         0.330000
25%         0.550000
50%         0.620000
75%         0.730000
max         2.000000
Name: sulphates, dtype: float64

In [23]:
df['alcohol'].describe()

count    1591.000000
mean       10.426053
std         1.066706
min         8.400000
25%         9.500000
50%        10.200000
75%        11.100000
max        14.900000
Name: alcohol, dtype: float64

In [24]:
df.corr()

,ID,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
ID,1.000000,-0.268371,-0.006833,-0.156712,-0.031780,-0.119930,0.085616,-0.115795,-0.368878,0.133390,-0.127397,0.242802,0.063376
fixed acidity,-0.268371,1.000000,-0.256737,0.672306,0.114839,0.093857,-0.150261,-0.110992,0.666876,-0.683788,0.184937,-0.061167,0.124958
volatile acidity,-0.006833,-0.256737,1.000000,-0.551511,0.001336,0.061202,-0.014598,0.074132,0.022504,0.234251,-0.261872,-0.203490,-0.389380
citric acid,-0.156712,0.672306,-0.551511,1.000000,0.143731,0.204294,-0.057619,0.038593,0.364181,-0.543230,0.313530,0.109561,0.224263
residual sugar,-0.031780,0.114839,0.001336,0.143731,1.000000,0.055471,0.187771,0.201975,0.355780,-0.086375,0.004876,0.041258,0.013377
chlorides,-0.119930,0.093857,0.061202,0.204294,0.055471,1.000000,0.006125,0.047543,0.200843,-0.265845,0.371465,-0.221720,-0.129036
free sulfur dioxide,0.085616,-0.150261,-0.014598,-0.057619,0.187771,0.006125,1.000000,0.667158,-0.018730,0.066752,0.051255,-0.072511,-0.049843
total sulfur dioxide,-0.115795,-0.110992,0.074132,0.038593,0.201975,0.047543,0.667158,1.000000,0.072720,-0.068603,0.042240,-0.206855,-0.184651
density,-0.368878,0.666876,0.022504,0.364181,0.355780,0.200843,-0.018730,0.072720,1.000000,-0.341037,0.149758,-0.496873,-0.174794
pH,0.133390,-0.683788,0.234251,-0.543230,-0.086375,-0.265845,0.066752,-0.068603,-0.341037,1.000000,-0.198338,0.204044,-0.058077
sulphates,-0.127397,0.184937,-0.261872,0.313530,0.004876,0.371465,0.051255,0.042240,0.149758,-0.198338,1.000000,0.092036,0.249878
alcohol,0.242802,-0.061167,-0.203490,0.109561,0.041258,-0.221720,-0.072511,-0.206855,-0.496873,0.204044,0.092036,1.000000,0.475444
quality,0.063376,0.124958,-0.389380,0.224263,0.013377,-0.129036,-0.049843,-0.184651,-0.174794,-0.058077,0.249878,0.475444,1.000000